version: '2'
services:
  pydio:
    build: pydio
    volumes_from:
      - stealthbox-conf
  flexget:
    build: flexget
  deluged:
    build: deluged
    restart: unless-stopped
    volumes_from:
      - stealthbox-conf
  deluge-web:
    build: deluge-web
    depends_on:
      - deluged
    restart: unless-stopped
    volumes_from:
      - stealthbox-conf
  sickrage:
    build: sickrage
    restart: unless-stopped
  couchpotato:
    build: couchpotato
    restart: unless-stopped
    volumes_from:
      - stealthbox-conf
      - stealthbox-tools
  headphones:
    build: headphones
    restart: unless-stopped
    volumes_from:
      - stealthbox-conf
      - stealthbox-tools
  sonarr:
    build: sonarr
    restart: unless-stopped
  ssl:
    build: ssl
  php-fpm:
    build: php-fpm
    volumes_from:
     - pydio
  nginx:
    build: nginx
    volumes_from:
     - pydio
     - ssl
    ports:
     - '50080:80'
     - '50443:443'
    depends_on:
     - pydio
     - php-fpm
     - deluge-web
     - sickrage
     - couchpotato
     - headphones
     - sonarr
  sshd:
    build: sshd
    ports:
     - '50022:22'
    volumes_from:
     - ssl
     - pydio
     - deluge-web
     - sickrage
     - couchpotato
     - headphones
     - sonarr
  stealthbox-tools:
    build: stealthbox-tools
  stealthbox-conf:
    build: stealthbox-conf
    volumes:
     - './stealthbox.json:/home/box/conf/stealthbox.json'
