version: '2'
networks:
  nginx-proxy:
    external: true
services:
  deluge-web:
    environment:
      VIRTUAL_HOST: deluge.${STEALTHBOX_DOMAIN}
      LETSENCRYPT_HOST: deluge.${STEALTHBOX_DOMAIN}
    networks:
      - default
      - nginx-proxy
  sickrage:
    environment:
      VIRTUAL_HOST: sickrage.${STEALTHBOX_DOMAIN}
      LETSENCRYPT_HOST: sickrage.${STEALTHBOX_DOMAIN}
    networks:
      - default
      - nginx-proxy
  couchpotato:
    environment:
      VIRTUAL_HOST: couchpotato.${STEALTHBOX_DOMAIN}
      LETSENCRYPT_HOST: couchpotato.${STEALTHBOX_DOMAIN}
    networks:
      - default
      - nginx-proxy
  headphones:
    environment:
      VIRTUAL_HOST: headphones.${STEALTHBOX_DOMAIN}
      LETSENCRYPT_HOST: headphones.${STEALTHBOX_DOMAIN}
    networks:
      - default
      - nginx-proxy
