version: '2'
services:
  pydio:
    build: pydio
    volumes_from:
      - stealthbox-conf
  flexget:
    build: flexget
  deluge:
    build: deluge
    restart: unless-stopped
    ports:
      - '8112:8112'
      - '58846:58846'
  sickrage:
    build: sickrage
    restart: unless-stopped
    ports:
      - '8074:8074'
  couchpotato:
    build: couchpotato
    restart: unless-stopped
    ports:
      - '5050:5050'
    volumes_from:
      - stealthbox-conf
      - stealthbox-tools
  headphones:
    build: headphones
    restart: unless-stopped
    ports:
      - '8181:8181'
    volumes_from:
      - stealthbox-conf
      - stealthbox-tools
  sonarr:
    build: sonarr
    restart: unless-stopped
    ports:
      - '8989:8989'
      - '9898:9898'
  ssl:
    build: ssl
  php-fpm:
    build: php-fpm
    ports:
     - '9000:9000'
    volumes_from:
     - pydio
  nginx:
    build: nginx
    volumes_from:
     - pydio
     - ssl
    ports:
     - '50080:80'
     - '50443:443'
    depends_on:
     - pydio
     - php-fpm
     - deluge
     - sickrage
     - couchpotato
     - headphones
     - sonarr
  sshd:
    build: sshd
    ports:
     - '50022:22'
    volumes_from:
     - ssl
     - pydio
     - deluge
     - sickrage
     - couchpotato
     - headphones
     - sonarr
  stealthbox-tools:
    build: stealthbox-tools
  stealthbox-conf:
    build: stealthbox-conf
    volumes:
     - './stealthbox.json:/home/box/conf/stealthbox.json'
