version: '2.2'
services:
  deluge-web:
    ports:
      - "${STEALTHBOX_PORTS_PREFIX}12:8112"
  nginx-standalone:
    image: nginx:alpine
    init: true
    ports:
     - "${STEALTHBOX_PORTS_PREFIX}80:80"
    volumes:
      - "./nginx-standalone/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx-standalone/proxy_params:/etc/nginx/proxy_params"
      - "./nginx-standalone/conf.d:/etc/nginx/conf.d"
    depends_on:
     - deluge-web
     - medusa
     - couchpotato
     - headphones
