version: '2.2'
networks:
  reverse-proxy:
    name: ${REVERSE_PROXY_NETWORK_NAME}
    external: true
services:
  deluge-web:
    environment:
      - VIRTUAL_HOST=deluge.${STEALTHBOX_DOMAIN}
      - VIRTUAL_PORT=8112
      - LETSENCRYPT_HOST=deluge.${STEALTHBOX_DOMAIN}
    networks:
      - default
      - reverse-proxy
  medusa:
    environment:
      - VIRTUAL_HOST=medusa.${STEALTHBOX_DOMAIN}
      - LETSENCRYPT_HOST=medusa.${STEALTHBOX_DOMAIN}
    networks:
      - default
      - reverse-proxy
  couchpotato:
    environment:
      - VIRTUAL_HOST=couchpotato.${STEALTHBOX_DOMAIN}
      - LETSENCRYPT_HOST=couchpotato.${STEALTHBOX_DOMAIN}
    networks:
      - default
      - reverse-proxy
  headphones:
    environment:
      - VIRTUAL_HOST=headphones.${STEALTHBOX_DOMAIN}
      - LETSENCRYPT_HOST=headphones.${STEALTHBOX_DOMAIN}
    networks:
      - default
      - reverse-proxy
