version: '2'
services:
  deluged:
    build: deluged
    restart: unless-stopped
    volumes_from:
      - stealthbox-conf
  deluge-web:
    build: deluge-web
    depends_on:
      - deluged
    restart: unless-stopped
    volumes_from:
      - stealthbox-conf
  sickrage:
    build: sickrage
    restart: unless-stopped
    volumes_from:
      - stealthbox-conf
      - stealthbox-tools
  couchpotato:
    build: couchpotato
    restart: unless-stopped
    volumes_from:
      - stealthbox-conf
      - stealthbox-tools
  headphones:
    build: headphones
    restart: unless-stopped
    volumes_from:
      - stealthbox-conf
      - stealthbox-tools
  sshd:
    build: sshd
    restart: unless-stopped
    ports:
     - "${STEALTHBOX_PORTS_PREFIX}22:22"
    volumes_from:
     - deluge-web
     - deluged
     - sickrage
     - couchpotato
     - headphones
  stealthbox-tools:
    build: stealthbox-tools
  stealthbox-conf:
    build: stealthbox-conf
    volumes:
     - './stealthbox.json:/home/box/conf/stealthbox.json'
